  Type: AWS::SQS::QueuePolicy
  Properties:
    PolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Sid: "Allow SNS publish to SQS"
          Effect: Allow
          Principal:
            Service: "sns.amazonaws.com"
          Resource: !GetAtt WaReceiveMessageSqs.Arn
          Action: SQS:SendMessage
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref WebhooksTopic
    Queues:
      - Ref: WaReceiveMessageSqs
